# Generated by Django 3.0.5 on 2020-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sheet', '0002_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(max_length=250),
        ),
    ]
